version: "2.24.3"

services:
  # Node.js service
  node-app:
    container_name: node-user-service
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - PG_DB=testDB
      - PG_USER=postgres
      - PG_PASSWORD=youssef
      - PG_HOST=postgres

  # PostgreSQL service
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: youssef
      POSTGRES_DB: testDB
    ports:
      - "5432:5432"
volumes:
  postgres-data: {}